apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ldoan
  labels:
    app: db
spec:
  replicas: <REPLICAS>
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/ldoan-harbor-project/db:971c881-d2d4070
        ports:
        - containerPort: 5432
