apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ldoan
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/ldoan-harbor-project/db:0f9f4d1-143f14f
        ports:
        - containerPort: 5432
